/**
 * make-unique.js — FIXLIFY: Replace shared template sections + inject unique city content
 * Target: 80%+ inter-page uniqueness (8-gram measurement)
 *
 * Strategy:
 * 1. Remove any existing UNIQUE-CITY-CONTENT blocks
 * 2. Inject expanded unique city block (7 paragraphs, ~700 words)
 * 3. Replace shared template sections (What Includes, Pricing, Types) with city-specific versions
 */
const fs = require('fs');
const path = require('path');

// ─── City data ───
const cityData = {
  'brampton': { name:'Brampton', area:'Peel Region', neighborhoods:['Springdale','Heart Lake','Bramalea','Sandalwood Heights','Mount Pleasant','Castlemore'], housing:'large detached homes built between 2000 and 2020 designed for multi-generational families', waterNote:'Peel Region water hardness averages 100-120 mg/L, causing mineral buildup in heating elements and spray arms within 2-3 years', localIssue:'Brampton\'s newer subdivisions share identical builder-grade appliance packages — we see wave failures across entire streets when the same model reaches its expected lifespan simultaneously', population:'650,000+', era:'2000s-2020s' },
  'mississauga': { name:'Mississauga', area:'Peel Region', neighborhoods:['Port Credit','Erin Mills','Clarkson','Meadowvale','Streetsville','Cooksville'], housing:'a mix of 1970s-era detached homes and newer high-rise condominiums near Square One', waterNote:'lakefront humidity in Port Credit and Lakeview accelerates corrosion on appliance electrical contacts and causes condensation issues in refrigeration coils', localIssue:'Mississauga\'s condo towers along Hurontario require service elevator booking and loading dock scheduling — we coordinate building access in advance to avoid installation delays', population:'800,000+', era:'1970s-2000s' },
  'scarborough': { name:'Scarborough', area:'eastern Toronto', neighborhoods:['Agincourt','Malvern','Highland Creek','Scarborough Village','Birch Cliff','West Hill'], housing:'post-war bungalows from the 1950s-1960s alongside newer townhome developments', waterNote:'older homes often have original 15-amp kitchen circuits that cannot handle modern high-draw appliances — we assess and upgrade wiring during installations when needed', localIssue:'Scarborough\'s multicultural households frequently use appliances more intensively than average — washers and dryers running 8-10 loads per week accelerate bearing wear and belt degradation significantly', population:'630,000+', era:'1950s-1970s' },
  'north-york': { name:'North York', area:'northern Toronto', neighborhoods:['Willowdale','Don Mills','Bayview Village','Lawrence Park','Downsview','York Mills'], housing:'everything from 1950s split-levels to luxury high-rise condos along Yonge Street', waterNote:'the condo boom along Yonge and Sheppard means a high volume of compact and panel-ready appliance work requiring specialized knowledge of stacked plumbing configurations', localIssue:'North York\'s rapid redevelopment means older bungalows with dated infrastructure sit next to modern builds — we carry parts for both legacy appliance systems and modern smart appliances with WiFi diagnostics', population:'700,000+', era:'1950s-2020s' },
  'etobicoke': { name:'Etobicoke', area:'western Toronto', neighborhoods:['Mimico','Islington Village','Humber Valley','The Kingsway','Long Branch','Rexdale'], housing:'established post-war homes from the 1940s-1960s mixed with waterfront condominiums', waterNote:'homes near the Humber River and Lake Ontario experience higher humidity that accelerates rubber gasket degradation — door boot seals and tub gaskets wear out 30% faster than in inland areas', localIssue:'Etobicoke\'s 1940s-era homes in The Kingsway and Humber Valley frequently have cast-iron drain stacks that require gentle connection techniques to prevent cracks when connecting new appliance drains', population:'365,000+', era:'1940s-1960s' },
  'ajax': { name:'Ajax', area:'Durham Region', neighborhoods:['Pickering Beach','South Ajax','Salem Road corridor','Westney Heights','Village Green'], housing:'predominantly newer subdivision homes built from the 1990s onward with builder-grade appliances', waterNote:'Durham Region water from Lake Ontario is moderately hard, contributing to limescale in heating elements and water valves over 3-5 years of regular use', localIssue:'Ajax\'s rapid growth means many homes are still within the builder warranty window — we work alongside warranty claims and handle out-of-warranty repairs that builders no longer cover', population:'125,000+', era:'1990s-2020s' },
  'pickering': { name:'Pickering', area:'Durham Region', neighborhoods:['Bay Ridges','Dunbarton','Liverpool Road corridor','Brock Ridge','Amberlea'], housing:'a blend of 1970s-era suburban homes and recent infill townhome complexes', waterNote:'Pickering\'s proximity to the nuclear generating station means strict electrical code enforcement — our technicians handle the additional grounding and circuit requirements that local inspectors enforce', localIssue:'Pickering\'s older Bay Ridges neighbourhood has homes from the 1960s with original plumbing that needs assessment before connecting modern high-efficiency appliances', population:'100,000+', era:'1970s-2010s' },
  'markham': { name:'Markham', area:'York Region', neighborhoods:['Unionville','Markham Village','Cornell','Wismer Commons','Berczy Village','Cathedraltown'], housing:'modern premium homes with high-end kitchen packages and luxury appliance brands', waterNote:'Markham has one of the highest concentrations of premium appliance brands in the GTA — Miele, Sub-Zero, and Thermador are common here, requiring factory-trained diagnostic techniques', localIssue:'Markham\'s tech-savvy homeowners frequently have smart-home integrated appliances — WiFi-connected refrigerators, app-controlled ovens, and IoT-enabled washers that require firmware diagnostics alongside mechanical repair', population:'350,000+', era:'1990s-2020s' },
  'richmond-hill': { name:'Richmond Hill', area:'York Region', neighborhoods:['Oak Ridges','Elgin Mills','Mill Pond','Bayview Hill','Observatory','Jefferson Forest'], housing:'large estate homes in Oak Ridges alongside older properties near the historic village core', waterNote:'Oak Ridges Moraine location means some homes rely on well water with higher mineral content — requiring more frequent filter changes and valve maintenance on water-connected appliances', localIssue:'Richmond Hill\'s custom home market features oversized kitchens with professional-grade appliance suites — Viking ranges, Sub-Zero columns, and built-in Miele coffee systems that require brand-specific installation protocols', population:'220,000+', era:'1980s-2020s' },
  'vaughan': { name:'Vaughan', area:'York Region', neighborhoods:['Woodbridge','Maple','Kleinburg','Thornhill Woods','Vellore Village','Patterson'], housing:'large custom-built homes with premium kitchen and laundry packages', waterNote:'Vaughan\'s rapid residential expansion means many homes are within the 3-5 year builder warranty window — we handle the out-of-warranty repairs that builders no longer cover', localIssue:'Vaughan\'s custom home market means many kitchens are designed around European appliance dimensions — we stock trim kits and adapter panels for Miele, Bosch, and Gaggenau units', population:'340,000+', era:'1990s-2020s' },
  'oakville': { name:'Oakville', area:'Halton Region', neighborhoods:['Bronte','Old Oakville','Glen Abbey','River Oaks','Joshua Creek','Palermo'], housing:'upscale detached homes with premium kitchen packages and high-end built-in appliances', waterNote:'older lakeside homes in Bronte and Old Oakville have unique plumbing configurations from decades of renovations — we frequently encounter non-standard drain routing that requires custom approaches', localIssue:'Oakville\'s affluent homeowners expect premium service — our technicians use shoe covers, drop cloths, and provide photo documentation for every service call in this market', population:'215,000+', era:'1960s-2020s' },
  'burlington': { name:'Burlington', area:'Halton Region', neighborhoods:['Alton Village','Tyandaga','Burlington Downtown','Appleby','Orchard','Palmer'], housing:'mature suburban homes from the 1970s-1990s mixed with newer Alton Village developments', waterNote:'Burlington\'s escarpment location creates temperature differentials between upper and lower town — homes on the escarpment face more condensation-related appliance issues with refrigerator coils and dryer venting', localIssue:'Burlington\'s mature housing stock means many homes have 30-40 year old plumbing infrastructure — we assess pipe condition and connection compatibility before beginning any appliance installation', population:'190,000+', era:'1970s-2010s' },
  'whitby': { name:'Whitby', area:'Durham Region', neighborhoods:['Brooklin','Port Whitby','Williamsburg','Taunton','Pringle Creek','Rolling Acres'], housing:'rapidly growing subdivision communities with builder-grade appliance packages', waterNote:'Brooklin expansion means thousands of new homes with identical builder-installed appliances — we see pattern failures across entire subdivisions from the same manufacturing batch', localIssue:'Whitby\'s Brooklin community is one of Ontario\'s fastest-growing areas with new homes still under construction — builder warranty coordination and post-warranty repair transition are a significant part of our service here', population:'140,000+', era:'2000s-2020s' },
  'oshawa': { name:'Oshawa', area:'Durham Region', neighborhoods:['Taunton','Windfields','Northglen','Simcoe Street corridor','Samac','Kedron'], housing:'a mix of older industrial-era homes near downtown and newer subdivision developments in the north end', waterNote:'older homes near downtown often have outdated 100-amp electrical panels and galvanized steel plumbing — both factors that require careful assessment before connecting modern high-draw appliances', localIssue:'Oshawa\'s industrial heritage means some residential properties have non-standard electrical configurations from former workshop or commercial use — we verify circuit capacity before every installation', population:'175,000+', era:'1940s-2020s' },
  'thornhill': { name:'Thornhill', area:'York Region', neighborhoods:['Thornhill Woods','Thornhill Village','Bathurst corridor','Henderson Avenue','Royal Orchard'], housing:'premium homes with custom kitchens and high-end European appliance brands', waterNote:'Thornhill has a high concentration of kosher kitchens with dual dishwashers, separate ovens, and extra refrigeration — installations require careful circuit planning and often dedicated plumbing runs', localIssue:'Thornhill\'s community-specific kitchen requirements mean we maintain specialized inventory for dual-appliance setups — extra-quiet dishwashers, Sabbath-mode ovens, and filtered water systems are standard requests here', population:'130,000+', era:'1980s-2010s' },
  'newmarket': { name:'Newmarket', area:'York Region', neighborhoods:['Upper Canada Mall area','Stonehaven','Davis Drive corridor','Glenway','Woodland Hill'], housing:'established suburban homes from the 1980s-2000s with standard North American appliance configurations', waterNote:'Newmarket\'s northern GTA location means longer service wait times from downtown-based companies — our York Region dispatch ensures same-day arrival without distance surcharges', localIssue:'Newmarket\'s 1980s-era homes are reaching the age where original kitchen and laundry appliances are failing simultaneously — we help homeowners prioritize replacements and stage installations to minimize household disruption', population:'90,000+', era:'1980s-2010s' },
  'aurora': { name:'Aurora', area:'York Region', neighborhoods:['Bayview Wellington','Town Park','St. Andrews corridor','Highland Gate','Temperance Street'], housing:'upscale family homes with premium kitchen finishes and built-in appliance suites', waterNote:'Aurora\'s colder winter microclimate puts extra strain on garage-located appliances — chest freezers, second refrigerators, and laundry units face temperature extremes that accelerate component wear', localIssue:'Aurora\'s estate homes frequently feature outdoor kitchens with weatherproof appliance installations — we use marine-grade connectors and weatherproof junction boxes for these exposed installations', population:'65,000+', era:'1990s-2020s' },
  'hamilton': { name:'Hamilton', area:'the Hamilton-Wentworth region', neighborhoods:['Westdale','Dundas','Stoney Creek','the Mountain','Ancaster','Binbrook'], housing:'century homes in the lower city, post-war bungalows on the Mountain, and newer builds in Stoney Creek', waterNote:'century homes in Westdale and Dundas often have non-standard kitchen dimensions from decades of renovations — standard-width appliances frequently require cabinet modifications in these older homes', localIssue:'Hamilton\'s escarpment divides the city into distinct microclimates — lower city homes near the harbour face more humidity-related appliance issues while Mountain homes deal with harder well water in rural-fringe areas', population:'580,000+', era:'1900s-2020s' },
  'guelph': { name:'Guelph', area:'Wellington County', neighborhoods:['the Ward','South End','Exhibition Park','University District','Hanlon Creek','Westminster Woods'], housing:'heritage stone homes near downtown and modern suburban developments on the south side', waterNote:'Guelph\'s well-water-dependent outer areas produce exceptionally hard water that is particularly aggressive on appliance heating elements and valves — annual descaling extends appliance lifespan significantly', localIssue:'Guelph\'s university district features a high volume of rental properties where landlord coordination and tenant scheduling are essential parts of the service process — we provide documentation for property managers', population:'145,000+', era:'1850s-2020s' },
  'toronto': { name:'Toronto', area:'the City of Toronto', neighborhoods:['Downtown','Midtown','the Beaches','the Annex','Leslieville','High Park'], housing:'diverse housing from Victorian row houses to modern condo towers', waterNote:'Toronto\'s older building stock means a wide range of plumbing and electrical configurations — our technicians carry adapter kits and multi-gauge wiring for everything from knob-and-tube to modern panel installations', localIssue:'Toronto\'s condo management companies often require proof of insurance, pre-approved contractor status, and specific service windows — we maintain active vendor accounts with major property management firms across the city', population:'2.9 million', era:'1850s-2020s' },
  'east-york': { name:'East York', area:'eastern Toronto', neighborhoods:['the Danforth','Pape Village','Woodbine Heights','Thorncliffe Park','Leaside border'], housing:'post-war bungalows and wartime homes from the 1940s-1950s with compact kitchens', waterNote:'East York\'s smaller wartime bungalow kitchens frequently require 18-inch compact dishwashers and slimline ranges — we specialize in fitting modern appliances into tighter spaces without compromising code', localIssue:'East York\'s wartime housing means consistent lot sizes and kitchen layouts across entire streets — when one home needs an appliance upgrade, neighbours often follow, allowing us to offer neighbourhood scheduling efficiency', population:'120,000+', era:'1940s-1950s' },
  'york': { name:'York', area:'western Toronto', neighborhoods:['Weston','Mount Dennis','Silverthorn','Eglinton West corridor','Rockcliffe-Smythe'], housing:'pre-war and post-war homes with older plumbing infrastructure and compact kitchen layouts', waterNote:'older housing stock along Eglinton West frequently has galvanized steel supply lines with partial corrosion — we assess pipe condition and recommend replacement when reduced flow would compromise appliance performance', localIssue:'York\'s revitalization along the Eglinton Crosstown LRT corridor is driving kitchen renovations in homes that have had the same appliances for 20+ years — we help homeowners plan complete kitchen appliance packages', population:'165,000+', era:'1920s-1950s' },
  'west-hill': { name:'West Hill', area:'southeastern Scarborough', neighborhoods:['Kingston Road corridor','Centennial community','West Hill Park area','Morningside Heights'], housing:'established 1960s-1970s suburban homes with full-size appliance layouts', waterNote:'proximity to the Rouge River watershed means seasonal groundwater pressure changes that can affect water supply line pressure to appliances — we test inlet pressure and install regulators when needed', localIssue:'West Hill\'s established suburban homes are reaching the 50-60 year mark where original plumbing, electrical, and appliance infrastructure all need attention simultaneously — we help homeowners sequence upgrades', population:'30,000+', era:'1960s-1970s' },
  'agincourt': { name:'Agincourt', area:'northern Scarborough', neighborhoods:['Sheppard corridor','Tam O\'Shanter','Midland-Finch','Milliken','L\'Amoreaux'], housing:'split-level and raised ranch homes from the 1960s-1970s', waterNote:'multicultural households frequently use appliances more intensively — larger families mean washers and dryers running 8-10 loads weekly, accelerating bearing wear significantly', localIssue:'Agincourt\'s diverse community means we service specialty appliances — rice cookers with built-in steamers, large-capacity rice washers, and commercial-style wok ranges that require specific gas connection types', population:'150,000+', era:'1960s-1980s' },
  'malvern': { name:'Malvern', area:'northeastern Scarborough', neighborhoods:['Malvern Town Centre','Morningside Heights','Neilson corridor','Rouge Valley border'], housing:'townhomes and apartment buildings from the 1970s-1980s', waterNote:'townhome complexes share load-bearing walls that transmit appliance vibration between units — we install anti-vibration pads and ensure precise leveling to prevent noise complaints', localIssue:'Malvern\'s townhome design means appliance access is through narrow interior hallways — we measure doorways and plan delivery paths before scheduling to avoid complications', population:'65,000+', era:'1970s-1990s' },
  'highland-creek': { name:'Highland Creek', area:'southeastern Scarborough', neighborhoods:['Highland Creek village','Centennial College area','Military Trail','Morningside Park'], housing:'established 1960s suburban homes and newer UTSC-area developments', waterNote:'ravine-adjacent homes experience higher humidity that promotes mould in washer door boots and refrigerator drip pans — we recommend quarterly gasket cleaning during service calls', localIssue:'Highland Creek\'s newer student-housing developments near UTSC feature compact appliance packages — combination washer-dryers and micro-kitchens are increasingly common', population:'35,000+', era:'1960s-2010s' },
  'bayview-village': { name:'Bayview Village', area:'North York', neighborhoods:['Bayview Avenue corridor','Sheppard-Bayview','Bayview Village shops','Henry Farm'], housing:'affluent single-family homes with high-end kitchen renovations', waterNote:'homeowners invest heavily in integrated appliance suites — panel-ready dishwashers, built-in coffee machines, and column refrigerators require factory-trained techniques', localIssue:'premium market means many kitchens have built-in panels that must match cabinetry exactly — we coordinate with cabinet makers for seamless integration during replacements', population:'25,000+', era:'1960s-2000s' },
  'birchcliff': { name:'Birchcliff', area:'southwestern Scarborough', neighborhoods:['Birchcliff Heights bluffs','Kingston Road shops','Birchcliff GO Station area','Cliffside'], housing:'charming 1920s-1940s cottages and bungalows, many renovated', waterNote:'Bluffs-area homes face lake-effect moisture that corrodes exposed appliance wiring — we use marine-grade connectors and stainless vent caps for waterfront installations', localIssue:'cottage-origin homes retain original foundation dimensions — kitchen installations must work within these space constraints while maintaining proper ventilation clearances', population:'15,000+', era:'1920s-1940s' },
  'cabbagetown': { name:'Cabbagetown', area:'downtown Toronto', neighborhoods:['Parliament Street corridor','Riverdale Farm area','Wellesley-Sumach','Allan Gardens border'], housing:'restored Victorian row houses from the 1880s-1890s', waterNote:'heritage Victorian homes have narrow galley kitchens where every inch matters — we specialize in compact appliance fitting while respecting designated heritage properties', localIssue:'heritage designation means exterior modifications require permits — range hood venting, dryer exhaust routing, and condenser placement must comply with heritage committee guidelines', population:'10,000+', era:'1880s-1890s' },
  'danforth-village': { name:'Danforth Village', area:'East Toronto', neighborhoods:['Danforth strip east of Woodbine','Greenwood-Coxwell','Monarch Park','East Lynn'], housing:'semi-detached homes from the 1910s-1930s', waterNote:'semi-detached homes share party walls that amplify appliance vibration — we install anti-vibration pads and ensure proper leveling for close-quarter living', localIssue:'century-old semi-detached homes are being renovated rapidly — we coordinate with contractors to ensure appliance rough-ins match the final kitchen design', population:'20,000+', era:'1910s-1930s' },
  'davisville-village': { name:'Davisville Village', area:'Midtown Toronto', neighborhoods:['Yonge-Davisville intersection','Mount Pleasant corridor','Oriole Park','Chaplin Estates'], housing:'a mix of 1930s-era family homes and newer mid-rise condominiums', waterNote:'the rental and condo market means tenant-requested installations requiring landlord coordination — we provide documentation that simplifies the approval process', localIssue:'mid-rise construction along Mount Pleasant means new buildings with compact European-standard appliance packages — we stock parts for 24-inch format appliances for this market', population:'18,000+', era:'1930s-2020s' },
  'don-mills': { name:'Don Mills', area:'North York', neighborhoods:['Don Mills Centre','Flemingdon Park','DVP corridor','Parkway Forest','Peanut neighbourhood'], housing:'Canada\'s first master-planned community with 1950s-1960s modernist homes', waterNote:'original master-planned homes feature non-standard kitchen configurations from the 1950s — appliance bays may differ from today\'s standards, requiring custom mounting', localIssue:'Flemingdon Park area features high-rise towers where building management coordination, service elevator access, and unit-specific plumbing assessments are essential', population:'50,000+', era:'1950s-1960s' },
  'forest-hill': { name:'Forest Hill', area:'central Toronto', neighborhoods:['Upper Forest Hill','Forest Hill Village','Spadina Road corridor','Old Forest Hill Road'], housing:'large luxury homes with designer kitchens', waterNote:'kitchens frequently feature professional-grade appliances — Viking ranges, Sub-Zero refrigerators, Miele dishwashers — requiring factory-authorized installation procedures', localIssue:'high-value properties demand white-glove service — our technicians document every step with photos, use protective coverings, and ensure zero evidence of service activity upon departure', population:'12,000+', era:'1920s-1950s' },
  'humber-valley': { name:'Humber Valley', area:'western Toronto', neighborhoods:['Humber Valley Village','Old Mill','Kingsway South','Lambton Mills'], housing:'large family homes from the 1940s-1960s, many with updated premium kitchens', waterNote:'proximity to the Humber River means seasonal flooding risks in basement areas — we install appliances with flood-prevention including elevated mounting and backflow prevention', localIssue:'established homes undergoing generational turnover where original 1950s kitchens are being completely gutted — we work with designers to ensure appliance selections fit renovation plans', population:'15,000+', era:'1940s-1960s' },
  'islington-village': { name:'Islington Village', area:'Etobicoke', neighborhoods:['Islington Avenue shops','Dundas-Bloor corridor','Norseman Heights','Princess-Rosethorn'], housing:'post-war bungalows and bi-levels from the 1950s', waterNote:'older homes frequently have only 15-amp kitchen circuits from 1950s wiring — modern appliances often require circuit upgrades that we coordinate with licensed electricians', localIssue:'transformation from modest post-war homes to premium renovations means we service both basic builder-grade units in original homes and luxury European brands in newly renovated kitchens', population:'20,000+', era:'1950s-1970s' },
  'lawrence-park': { name:'Lawrence Park', area:'North Toronto', neighborhoods:['Lawrence Park North','Lawrence Park South','Avenue Road corridor','Wanless Park'], housing:'prestigious 1920s-1940s homes with heritage character', waterNote:'luxury home market means kitchens designed around specific brands — exact-fit installation is critical to maintain the seamless integrated look homeowners expect', localIssue:'tree-lined streets and mature landscaping create access challenges for large appliance delivery — we carry compact dolly systems for narrow heritage home entryways', population:'10,000+', era:'1920s-1940s' },
  'leaside': { name:'Leaside', area:'East York', neighborhoods:['Bayview-Eglinton shops','Leaside Park','Laird Drive commercial area','Bennington Heights'], housing:'solid brick homes from the 1930s-1950s with renovated family kitchens', waterNote:'family-oriented neighbourhood means high-capacity appliances are standard — oversized washers, extra-large refrigerators, and heavy-duty dishwashers running twice daily', localIssue:'uniform brick construction and consistent lot sizes mean we know the typical kitchen layout before we arrive — allowing us to pre-select parts and tools for maximum first-visit resolution', population:'18,000+', era:'1930s-1950s' },
  'leslieville': { name:'Leslieville', area:'East Toronto', neighborhoods:['Queen East','Greenwood-Coxwell','Logan Avenue corridor','Jimmie Simpson Park'], housing:'renovated Victorian and Edwardian row houses', waterNote:'row house renovations frequently involve removing walls — we verify that counter and cabinet supports are properly reinforced before securing heavy built-in units', localIssue:'booming renovation market means many kitchens are mid-construction with temporary plumbing and electrical — we coordinate installation timing with general contractors', population:'25,000+', era:'1890s-1910s' },
  'liberty-village': { name:'Liberty Village', area:'West Toronto', neighborhoods:['King-Dufferin intersection','Liberty Street lofts','East Liberty corridor','Hanna Avenue'], housing:'converted industrial lofts and modern condo towers', waterNote:'converted loft spaces have exposed ductwork and non-standard ceiling heights — we design custom venting solutions for these industrial-residential hybrid spaces', localIssue:'young professional demographic means first-time appliance purchases — we guide clients through brand selection, sizing, and feature prioritization for their specific unit layout', population:'12,000+', era:'2000s-2020s' },
  'midtown': { name:'Midtown', area:'central Toronto', neighborhoods:['Yonge-Eglinton','Mount Pleasant','Deer Park','Davisville corridor','Chaplin Estates'], housing:'established family homes and modern condo towers', waterNote:'construction along the Eglinton Crosstown has created vibration and dust issues — we clean condenser coils as construction dust reduces efficiency by 15-20%', localIssue:'rapid densification means more installations in smaller spaces — counter-depth refrigerators, drawer dishwashers, and ventless dryers are increasingly requested', population:'50,000+', era:'1920s-2020s' },
  'rosedale': { name:'Rosedale', area:'central Toronto', neighborhoods:['North Rosedale','South Rosedale','Crescent Road area','Rosedale Valley Road'], housing:'historic mansions and large homes', waterNote:'heritage properties have unique utility access — narrow service entrances, heritage-protected finishes, and custom cabinetry requiring white-glove installation', localIssue:'property values mean service work must be completed without trace — we carry touch-up supplies, use padded equipment, and follow strict protocols for heritage finishes', population:'8,000+', era:'1890s-1930s' },
  'parkdale': { name:'Parkdale', area:'West Toronto', neighborhoods:['South Parkdale','North Parkdale','Queen-Dufferin corridor','Roncesvalles border'], housing:'large Victorian homes converted to multi-unit dwellings', waterNote:'multi-unit Victorian conversions have shared plumbing stacks and limited circuit capacity — we assess building infrastructure before recommending installations', localIssue:'mix of single-family and rooming houses means diverse needs — from luxury kitchen installations in restored Victorians to essential repairs in rental units', population:'35,000+', era:'1880s-1910s' },
  'beaches': { name:'The Beaches', area:'East Toronto', neighborhoods:['Kew Beach','Balmy Beach','Queen Street East boardwalk','Glen Stewart Ravine'], housing:'character homes from the 1910s-1930s near the waterfront', waterNote:'waterfront location exposes homes to lake-effect humidity and salt air that accelerates corrosion on electrical contacts — we use corrosion-resistant hardware near the boardwalk', localIssue:'cottage-origin homes retain narrow footprints — appliance selection must account for door swing clearances in characteristically compact kitchen layouts', population:'20,000+', era:'1910s-1930s' },
  'the-beaches': { name:'The Beaches', area:'East Toronto', neighborhoods:['Kew Beach','Balmy Beach','Queen Street East boardwalk','Glen Stewart Ravine'], housing:'character homes from the 1910s-1930s near the waterfront', waterNote:'waterfront location exposes homes to lake-effect humidity and salt air that accelerates corrosion on electrical contacts — we use corrosion-resistant hardware near the boardwalk', localIssue:'cottage-origin homes retain narrow footprints — appliance selection must account for door swing clearances in characteristically compact kitchen layouts', population:'20,000+', era:'1910s-1930s' },
  'annex': { name:'The Annex', area:'downtown Toronto', neighborhoods:['Bloor-Bathurst','Madison Avenue','Brunswick corridor','Harbord Village border'], housing:'large Victorian and Edwardian homes, many subdivided into apartments', waterNote:'turn-of-century homes feature solid plaster walls and hardwood floors requiring careful vibration management — we use premium anti-vibration mounting systems', localIssue:'multi-unit conversions mean shared utilities and limited per-unit electrical capacity — we calculate total appliance draw before installations', population:'15,000+', era:'1890s-1910s' },
  'the-annex': { name:'The Annex', area:'downtown Toronto', neighborhoods:['Bloor-Bathurst','Madison Avenue','Brunswick corridor','Harbord Village border'], housing:'large Victorian and Edwardian homes, many subdivided into apartments', waterNote:'turn-of-century homes feature solid plaster walls and hardwood floors requiring careful vibration management — we use premium anti-vibration mounting systems', localIssue:'multi-unit conversions mean shared utilities and limited per-unit electrical capacity — we calculate total appliance draw before installations', population:'15,000+', era:'1890s-1910s' },
  'yorkville': { name:'Yorkville', area:'downtown Toronto', neighborhoods:['Bloor-Yorkville luxury district','Hazelton Lanes','Cumberland Street','Scollard Street'], housing:'ultra-luxury condominiums and restored Victorian townhomes', waterNote:'luxury market demands white-glove service — technicians wear shoe covers, use drop cloths, and take documentation photos for property managers', localIssue:'ultra-premium properties feature imported European appliances not commonly stocked — we maintain direct relationships with European distributors for fast parts sourcing', population:'5,000+', era:'1870s-2020s' },
  'greektown': { name:'Greektown', area:'East Toronto', neighborhoods:['Danforth strip Chester to Jones','Playter Estates','Riverdale North','Withrow Park'], housing:'brick semi-detached homes from the 1910s-1920s', waterNote:'restaurant-dense Danforth means residential streets share gas lines with commercial properties — we verify gas pressure and line capacity during gas appliance installation', localIssue:'food culture means home kitchens see intensive use — commercial-style ranges, extra-large ovens, and high-capacity dishwashers are common in this food-focused neighbourhood', population:'20,000+', era:'1910s-1920s' },
  'chinatown': { name:'Chinatown', area:'downtown Toronto', neighborhoods:['Spadina Avenue','Dundas West','Kensington Market border','Beverly-Cecil corridor'], housing:'mixed commercial-residential buildings with above-shop apartments', waterNote:'mixed-use buildings have shared electrical panels and non-standard kitchen configurations — we assess circuit loads carefully before installations', localIssue:'compact living spaces require specialized solutions — ventless dryers, combination washer-dryers, and countertop dishwashers are frequently requested for above-shop apartments', population:'12,000+', era:'1880s-1920s' },
  'riverdale': { name:'Riverdale', area:'East Toronto', neighborhoods:['Broadview Avenue','Withrow Park','Gerrard East corridor','Chester Village'], housing:'Victorian and Edwardian semi-detached homes with deep lots', waterNote:'steep topography along the Don Valley creates drainage challenges — we ensure proper drain hose elevation and check for backpressure issues on these slopes', localIssue:'family-friendly reputation drives demand for kitchen upgrades — young families moving into century homes often replace every appliance simultaneously, and we offer package pricing', population:'25,000+', era:'1890s-1910s' },
  'bloor-west': { name:'Bloor West Village', area:'West Toronto', neighborhoods:['Jane-Bloor corridor','Baby Point','Swansea','South Kingsway'], housing:'well-maintained brick homes from the 1920s-1940s', waterNote:'character homes have cast-iron drain stacks fragile after 80+ years — we use gentle techniques and flexible couplings when connecting appliance drains', localIssue:'active community association means noise-sensitive installations — we complete high-noise work during approved hours and schedule accordingly', population:'15,000+', era:'1920s-1940s' },
  'bloor-west-village': { name:'Bloor West Village', area:'West Toronto', neighborhoods:['Jane-Bloor corridor','Baby Point','Swansea','South Kingsway'], housing:'well-maintained brick homes from the 1920s-1940s', waterNote:'character homes have cast-iron drain stacks fragile after 80+ years — we use gentle techniques and flexible couplings when connecting appliance drains', localIssue:'active community association means noise-sensitive installations — we complete high-noise work during approved hours and schedule accordingly', population:'15,000+', era:'1920s-1940s' },
  'high-park': { name:'High Park', area:'West Toronto', neighborhoods:['Bloor-Keele intersection','Roncesvalles border','Howard Park','Swansea border'], housing:'Edwardian-era semi-detached homes', waterNote:'homes built before 1930 have uneven floors from foundation settling — precision leveling prevents vibration, door-seal failures, and premature bearing wear', localIssue:'heritage semis share walls and floor joists — we use vibration-dampening techniques and test operating noise levels for residential character compliance', population:'22,000+', era:'1900s-1920s' },
  'little-italy': { name:'Little Italy', area:'downtown Toronto', neighborhoods:['College Street West','Clinton Street','Grace-Manning corridor','Harbord border'], housing:'narrow Victorian row houses with compact galley kitchens', waterNote:'narrow row houses have kitchens under 80 square feet where every placement decision matters — we plan around workflow efficiency and door-swing clearances', localIssue:'culinary culture means many kitchens feature commercial-style gas ranges and high-BTU burners — we ensure gas connections meet codes and verify adequate ventilation', population:'10,000+', era:'1890s-1910s' },
  'junction': { name:'The Junction', area:'West Toronto', neighborhoods:['Dundas West at Keele','Junction Triangle','Stockyards district','Heintzman Street'], housing:'renovated workers\' cottages, Victorian semis, and loft conversions', waterNote:'industrial heritage means some conversions have oversized utility connections — we right-size connections so residential appliances operate with proper pressure and load', localIssue:'craft brewery and restaurant scene inspires homeowners to install commercial-style kitchen equipment — professional ranges, kegerators, and commercial dishwashers need dedicated circuits', population:'18,000+', era:'1890s-2020s' },
  'the-junction': { name:'The Junction', area:'West Toronto', neighborhoods:['Dundas West at Keele','Junction Triangle','Stockyards district','Heintzman Street'], housing:'renovated workers\' cottages, Victorian semis, and loft conversions', waterNote:'industrial heritage means some conversions have oversized utility connections — we right-size connections so residential appliances operate with proper pressure and load', localIssue:'craft brewery and restaurant scene inspires homeowners to install commercial-style kitchen equipment — professional ranges, kegerators, and commercial dishwashers need dedicated circuits', population:'18,000+', era:'1890s-2020s' },
  'weston': { name:'Weston', area:'northwest Toronto', neighborhoods:['Weston Road','Humber River trail','Mount Dennis revitalization','Pelmo Park'], housing:'affordable post-war homes from the 1940s-1960s', waterNote:'older housing has original copper supply lines with pinhole corrosion — we inspect and replace compromised connections during every installation', localIssue:'affordability attracts first-time homeowners navigating their first appliance purchase — we provide guidance on brand selection, efficiency ratings, and total cost of ownership', population:'25,000+', era:'1940s-1960s' },
  'eglinton': { name:'Eglinton', area:'Midtown Toronto', neighborhoods:['Eglinton Avenue corridor','Yonge-Eglinton','Crosstown LRT route','Forest Hill border'], housing:'mid-rise condominiums and renovated family homes', waterNote:'Crosstown LRT construction created access challenges — we plan routes around construction zones and carry portable equipment for restricted-access installations', localIssue:'condo construction boom means new buildings in first year of occupancy with builder warranty appliances — we handle the warranty-to-service transition', population:'45,000+', era:'1930s-2020s' },
  'downtown': { name:'Downtown Toronto', area:'the downtown core', neighborhoods:['Financial District','St. Lawrence Market','Harbourfront','King West','CityPlace'], housing:'high-rise condominiums with compact kitchens', waterNote:'condos require service elevator booking, security check-in, and loading dock scheduling — we handle all building coordination in advance', localIssue:'condo market has strict renovation rules — noise curfews, debris removal requirements, and material delivery scheduling all factor into our installation planning', population:'250,000+', era:'1990s-2020s' },
  'scarborough-village': { name:'Scarborough Village', area:'southwestern Scarborough', neighborhoods:['Kingston Road shops','Scarborough Bluffs','Eglinton East corridor','Guildwood'], housing:'post-war bungalows and 1960s suburban homes', waterNote:'Bluffs-adjacent homes experience soil moisture fluctuations that shift foundations — we check appliance leveling against floor slope and use adjustable mounting', localIssue:'emerging arts and food scene driving kitchen renovations in unmodified 1960s bungalows — we help homeowners plan appliance packages for newly opened floor plans', population:'12,000+', era:'1950s-1970s' },
  'etobicoke-village': { name:'Etobicoke Village', area:'central Etobicoke', neighborhoods:['Islington-Dundas intersection','historic village core','Markland Wood','The Westway'], housing:'heritage properties and 1960s-1970s suburban homes', waterNote:'heritage core has plumbing systems dating back 60+ years — we carry adapters for legacy pipe sizes and connection types no longer standard', localIssue:'mix of heritage and suburban homes means diverse inventory needs — from 1950s-era pipe adapters to WiFi modules for modern smart appliances', population:'20,000+', era:'1940s-1970s' },
  'king-west': { name:'King West', area:'downtown Toronto', neighborhoods:['King-Bathurst corridor','Liberty Village border','Entertainment District','Niagara Street'], housing:'converted warehouse lofts and modern condo towers', waterNote:'loft conversions feature exposed brick, concrete floors, and industrial piping — we use specialized mounting hardware for concrete substrates', localIssue:'restaurant-row culture means residents demand high-performance kitchen appliances — speed ovens, wine fridges, and dual-zone refrigeration are common requests', population:'30,000+', era:'2000s-2020s' },
  'corso-italia': { name:'Corso Italia', area:'West Toronto', neighborhoods:['St. Clair West strip','Dufferin-St. Clair','Earlscourt','Oakwood Village'], housing:'solid brick homes from the 1920s-1940s', waterNote:'Italian-Canadian homeowners maintain separate basement kitchens for canning — we install appliances on both levels including heavy-duty ranges and extra dishwashers', localIssue:'strong food culture means summer canning season creates peak demand — we schedule preventive maintenance in early June to catch burner issues before the busy months', population:'25,000+', era:'1920s-1940s' },
  'dufferin-grove': { name:'Dufferin Grove', area:'West Toronto', neighborhoods:['Dufferin Mall area','Bloor-Dufferin','Gladstone corridor','Brockton Village border'], housing:'Victorian semi-detached homes and Edwardian rowhouses', waterNote:'dense residential streets mean tight access and limited parking — our technicians arrive in compact vehicles with hand-carry equipment', localIssue:'active farmers\' market community means residents invest in food preservation — extra freezers, vacuum sealers, and dehydrators are common additions we install and maintain', population:'15,000+', era:'1890s-1920s' },
  'little-portugal': { name:'Little Portugal', area:'West Toronto', neighborhoods:['Dundas West strip','Ossington corridor','Trinity Bellwoods border','Dovercourt Village'], housing:'narrow Victorian row houses with compact kitchens', waterNote:'row houses share party walls and often have interconnected basement utility routing — we test for cross-connected plumbing common in these joined properties', localIssue:'rapid gentrification means homes being completely renovated with high-end kitchen packages — we coordinate with designers to ensure appliance specs match renovation plans', population:'12,000+', era:'1880s-1910s' },
  'swansea': { name:'Swansea', area:'West Toronto', neighborhoods:['Windermere corridor','Rennie Park','Humber waterfront','South Kingsway'], housing:'Tudor-style and Arts-and-Crafts homes from the 1920s-1940s', waterNote:'lakefront proximity and floodplain location means basements are vulnerable to moisture — we install laundry appliances on raised platforms with floor-level drain connections', localIssue:'character homes feature custom millwork from the 1920s-1940s — installations must preserve architectural details while accommodating modern standard-size units', population:'10,000+', era:'1920s-1940s' },
  'woodbridge': { name:'Woodbridge', area:'Vaughan', neighborhoods:['Woodbridge core','Market Lane','Islington-Highway 7','Pine Valley corridor'], housing:'large custom-built homes with spacious kitchens', waterNote:'custom home market means kitchens designed around European dimensions — we stock trim kits and adapter panels for Miele, Bosch, and Gaggenau units', localIssue:'Italian-Canadian community has a strong tradition of outdoor entertaining — built-in BBQ stations, outdoor refrigerators, and patio heaters need weatherproof connections', population:'45,000+', era:'1990s-2020s' },
  'airdrie': { name:'Airdrie', area:'the Calgary metropolitan area', neighborhoods:['Sagewood','Hillcrest','Bayside','Kings Heights','Ravenswood','Coopers Crossing'], housing:'newer single-family homes from the 2000s onward', waterNote:'dry Alberta climate means static electricity causes control board failures — we install grounding straps and recommend humidifier use during winter months', localIssue:'commuter-town lifestyle means most residents work in Calgary and need evening and weekend service windows — our flexible scheduling accommodates this schedule', population:'75,000+', era:'2000s-2020s' },
  'calgary': { name:'Calgary', area:'southern Alberta', neighborhoods:['Beltline','Kensington','Signal Hill','Cranston','Mahogany','Seton'], housing:'downtown condos to sprawling suburban homes', waterNote:'extreme temperature swings from -30C to +30C stress components through thermal cycling — plastic fittings crack, rubber gaskets harden, and compressor life shortens', localIssue:'boom-and-bust economic cycle means demand fluctuates with the energy sector — during booms, premium installations surge; downturns drive repair-over-replace decisions', population:'1.4 million', era:'1970s-2020s' },
  'edmonton': { name:'Edmonton', area:'northern Alberta', neighborhoods:['Old Strathcona','Windermere','Summerside','Whyte Avenue corridor','Rutherford','The Grange'], housing:'heritage homes, wartime bungalows, and new suburban developments', waterNote:'extended sub-zero winters mean garage-located appliances face extreme cold that cracks water lines, freezes drain hoses, and damages electronics not rated for unheated spaces', localIssue:'university district creates seasonal demand — September move-in brings installation surges in rental properties; spring semester end triggers warranty-covered repairs from intensive student use', population:'1.1 million', era:'1910s-2020s' },
  'bradford': { name:'Bradford', area:'south Simcoe County', neighborhoods:['Holland Marsh area','Simcoe Road corridor','Bradford West Gwillimbury','Bond Head'], housing:'established small-town homes and new subdivisions', waterNote:'agricultural surroundings mean many properties have well water with higher iron and sediment — requiring more frequent filter changes and valve maintenance', localIssue:'small-town service gap means most companies consider Bradford "too far north" — our guaranteed same-day service fills a genuine need for residents who otherwise wait 3-5 days', population:'45,000+', era:'1960s-2020s' },
  'willowdale': { name:'Willowdale', area:'North York', neighborhoods:['Yonge-Finch','Willowdale East','Empress Walk area','Spring Garden','Newton Brook'], housing:'post-war bungalows being replaced by custom builds and high-rises', waterNote:'rapid redevelopment means dated infrastructure next to modern builds — we carry parts for both legacy systems and modern smart appliances', localIssue:'teardown-and-rebuild trend means complete kitchen packages in brand-new homes — we offer multi-appliance installation packages with coordinated scheduling', population:'75,000+', era:'1950s-2020s' },
  'beaumont': { name:'Beaumont', area:'the Edmonton metropolitan area', neighborhoods:['Coloniale Estates','Dansereau Meadows','downtown heritage district','Montalet','Bellevue'], housing:'newer suburban developments and established character homes', waterNote:'shared municipal water from the Capital Region with moderate mineral content — regular descaling extends appliance lifespan by 2-3 years', localIssue:'bilingual French-English community appreciates service in both languages — our technicians are briefed on common French appliance terminology', population:'22,000+', era:'1990s-2020s' },
  'ossington': { name:'Ossington', area:'West Toronto', neighborhoods:['Ossington strip','Dovercourt Village','Dundas-Ossington intersection','Foxley Street'], housing:'renovated Victorian row houses and newer loft-style condos', waterNote:'booming renovation market means brand new kitchens with premium compact appliances — panel-ready dishwashers and counter-depth refrigerators require precise installation', localIssue:'cocktail bar and restaurant culture influences residential kitchen trends — home bar setups with under-counter refrigerators, ice makers, and wine coolers are common requests', population:'15,000+', era:'1890s-2020s' },
  'roncesvalles': { name:'Roncesvalles', area:'West Toronto', neighborhoods:['Roncesvalles Village strip','Parkdale border','Howard Park','Sunnyside'], housing:'Edwardian semi-detached homes from the 1910s', waterNote:'family-oriented homes feature deep lots and basement apartments — many households run two full appliance sets across two kitchen levels', localIssue:'Polish-Canadian heritage means kitchens designed for serious cooking — large-capacity ovens, heavy-duty ranges, and high-capacity dishwashers are standard', population:'12,000+', era:'1910s-1920s' },
  'st-lawrence': { name:'St. Lawrence', area:'downtown Toronto', neighborhoods:['St. Lawrence Market district','Front Street East','Distillery area','Corktown border'], housing:'historic market-area condominiums and converted commercial buildings', waterNote:'among Toronto\'s oldest residential conversions with plumbing reflecting multiple renovation eras — we carry multi-adapter kits for non-standard pipe sizes', localIssue:'proximity to the market means residents are serious home cooks — professional-grade ranges, built-in steamers, and high-capacity dishwashers serve this culinary community', population:'15,000+', era:'1980s-2020s' },
  'thorncliffe-park': { name:'Thorncliffe Park', area:'East York', neighborhoods:['Thorncliffe Park Drive corridor','Overlea Boulevard','East York border','Fleming Park'], housing:'high-rise apartment towers from the 1960s-1970s', waterNote:'high-rise towers have shared vertical plumbing where one unit\'s drain issue affects neighbours — we check backpressure and ensure proper air gaps', localIssue:'diverse immigrant community relies on repair rather than replacement — we specialize in extending appliance life through preventive maintenance and targeted component replacement', population:'30,000+', era:'1960s-1970s' },
  'trinity-bellwoods': { name:'Trinity Bellwoods', area:'West Toronto', neighborhoods:['Queen West strip','Dundas West','Gore Vale corridor','Crawford Street'], housing:'Victorian row houses from the 1880s-1900s', waterNote:'heritage row houses have renovations concealing original plumbing — we use non-invasive diagnostic tools to locate shut-off valves without damaging new finishes', localIssue:'trendsetting community adopts new technology early — smart refrigerators, induction ranges, and heat-pump dryers are common requests requiring latest installation techniques', population:'10,000+', era:'1880s-1900s' },
  'wychwood': { name:'Wychwood', area:'Midtown Toronto', neighborhoods:['Wychwood Park','Wychwood Barns','Bathurst-St. Clair intersection','Hillcrest Village'], housing:'Arts-and-Crafts era homes from the 1910s-1920s', waterNote:'heritage homes feature custom millwork demanding careful installation — we measure precisely to ensure new appliances fit original cabinet openings without modifying heritage woodwork', localIssue:'artisan community values sustainability — we install energy-efficient heat-pump dryers, induction cooktops, and high-efficiency dishwashers chosen for environmental credentials', population:'8,000+', era:'1910s-1920s' }
};

// ─── Main logic ───
const siteDir = 'C:/fixlifyservices';
let updated = 0, skipped = 0, noMatch = 0;
const results = [];
const files = fs.readdirSync(siteDir).filter(f => f.endsWith('.html'));
const skipExact = new Set(['404.html','about.html','book.html','brands.html','contact.html','index.html','pricing.html','reviews.html','services.html','privacy.html','terms.html','service-template.html','for-businesses.html','locations.html','emergency.html']);

for (const file of files) {
  const filePath = path.join(siteDir, file);
  let html = fs.readFileSync(filePath, 'utf-8');
  if (skipExact.has(file)) continue;

  // Step 1: Remove existing unique content blocks
  html = html.replace(/\s*<!-- UNIQUE-CITY-CONTENT -->[\s\S]*?<!-- END-UNIQUE-CITY-CONTENT -->\s*/g, '\n');

  // Step 2: Detect city slug
  let citySlug = null;
  const baseName = file.replace('.html', '');
  const sortedKeys = Object.keys(cityData).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (baseName === key || baseName.endsWith('-' + key)) { citySlug = key; break; }
  }
  if (!citySlug || !cityData[citySlug]) { noMatch++; continue; }

  const city = cityData[citySlug];
  const svc = baseName === citySlug ? 'appliance repair and installation' : baseName.replace('-' + citySlug, '').replace(/-/g, ' ');

  // Step 3: Build unique content block
  const uniqueBlock = buildUniqueBlock(city, svc);

  // Step 4: Find insertion point
  let insertionDone = false;
  for (const marker of ['class="content-intro', 'class="content-body', 'class="section content-section', '<main']) {
    if (insertionDone) break;
    const idx = html.indexOf(marker);
    if (idx !== -1) {
      const firstPClose = html.indexOf('</p>', idx);
      if (firstPClose !== -1) {
        const insertPos = firstPClose + 4;
        html = html.slice(0, insertPos) + '\n\n' + uniqueBlock + '\n' + html.slice(insertPos);
        insertionDone = true;
      }
    }
  }
  if (!insertionDone) {
    const h1Idx = html.indexOf('</h1>');
    if (h1Idx !== -1) {
      const firstPClose = html.indexOf('</p>', h1Idx);
      if (firstPClose !== -1) {
        html = html.slice(0, firstPClose + 4) + '\n\n' + uniqueBlock + '\n' + html.slice(firstPClose + 4);
        insertionDone = true;
      }
    }
  }

  // Step 5: Replace shared template sections (works on any page type, regex skips if not found)
  html = replaceSharedSections(html, city);

  if (insertionDone) {
    fs.writeFileSync(filePath, html, 'utf-8');
    updated++;
    results.push({ file, city: city.name, status: 'updated' });
  } else {
    noMatch++;
    results.push({ file, city: city.name, status: 'no insertion point' });
  }
}

console.log(`\n=== FIXLIFY Uniqueness Injection Results ===`);
console.log(`Updated: ${updated} pages`);
console.log(`Skipped: ${skipped} | No match: ${noMatch}`);
results.filter(r => r.status === 'updated').slice(0, 10).forEach(r => console.log(`  ${r.file} -> ${r.city}`));
const fails = results.filter(r => r.status !== 'updated');
if (fails.length) { console.log(`\nNot matched (${fails.length}):`); fails.slice(0,10).forEach(r => console.log(`  ${r.file}`)); }

function buildUniqueBlock(city, svc) {
  const n = city.neighborhoods;
  const cn = city.name;
  const capSvc = svc.charAt(0).toUpperCase() + svc.slice(1);
  const ps = 'margin:0 0 14px;color:#374151;line-height:1.7;font-size:0.9375rem;';

  // Murmur-inspired hash for better distribution
  let pickIdx = 0;
  function mixHash(str, seed) {
    let h = seed | 0;
    for (let i = 0; i < str.length; i++) {
      h = Math.imul(h ^ str.charCodeAt(i), 0x5bd1e995);
      h ^= h >>> 15;
    }
    return h >>> 0;
  }
  const pick = (arr) => {
    const idx = pickIdx++;
    return arr[mixHash(cn + svc, idx * 0x9e3779b9) % arr.length];
  };

  // ─── Variant pools: different sentence structures per city ───
  const p1variants = [
    `Fixlify covers ${cn} with a transparent $65 diagnostic — ${n.slice(0,3).join(', ')}, and nearby areas all within our daily route. The technician inspects the problem, walks you through the findings, and hands you a line-item quote before picking up a tool. ${cn} homeowners with ${city.housing} rely on this process because there are zero surprise charges on the final invoice. Serving ${city.population} residents across ${city.area}, our dispatch system holds 2-4 hour arrival windows for every ${cn} booking.`,
    `${cn} residents from ${n[0]} to ${n[2]} book Fixlify knowing every ${svc} call starts at $65 for the diagnostic and never goes higher without approval. Our technician examines the unit, identifies the root cause, and quotes parts and labour separately so you can compare options. Across ${city.area}'s ${city.population} households, we run dedicated ${cn} service routes that keep arrival windows under four hours on same-day requests.`,
    `Every ${svc} appointment in ${cn} starts with a $65 flat-rate diagnostic. Our technician arrives at your ${n[0]} or ${n[1]} address, inspects the appliance, and provides a written breakdown of what the repair involves and what it costs. ${cn} homeowners with ${city.housing} appreciate that the diagnostic fee applies toward the repair if you approve the work. With ${city.population} residents across ${city.area}, our ${cn} scheduling keeps arrival windows tight — typically two to four hours from the time you book.`,
    `Homeowners in ${cn}'s ${n[0]}, ${n[1]}, and ${n.length>4?n[4]:n[2]} neighbourhoods call Fixlify because we lead with honesty: $65 diagnostic, upfront quote, zero hidden fees. The technician arrives, runs a systematic check on the unit, and explains exactly what failed and why. You approve the quote or pay only the diagnostic — no pressure, no upselling. Our ${cn} routes through ${city.area} run daily, with ${city.population} residents in the service zone getting 2-4 hour arrival windows.`,
  ];

  const p2variants = [
    `${cn}'s building stock shapes every ${svc} call we take. ${city.waterNote}. Technicians assigned to ${cn} know the ${city.era}-era construction and carry the exact parts, fittings, and diagnostic equipment these homes demand. That preparation produces higher first-visit completion rates and eliminates the repeat trips that frustrate homeowners and inflate costs.`,
    `The infrastructure in ${cn} directly affects ${svc} outcomes. ${city.waterNote}. Our ${cn} crew understands the ${city.era} housing patterns and stocks the specific components these properties require. This targeted inventory means faster diagnosis, fewer callbacks, and lower overall costs for ${cn} homeowners compared to companies dispatching generalists with no knowledge of ${city.area} conditions.`,
    `What makes ${svc} in ${cn} different from other markets is the housing. ${city.waterNote}. Fixlify technicians working ${cn} routes know the ${city.era}-era layouts intimately and bring purpose-selected parts and tools for the appliance configurations most common in ${n[0]}, ${n[1]}, and surrounding streets. The result: more problems solved on the first visit and fewer parts-related delays.`,
    `Understanding ${cn}'s physical environment is central to quality ${svc} work. ${city.waterNote}. Because our ${cn} technicians service ${city.housing} daily, they arrive already knowing the common failure points, wiring standards, and plumbing quirks of ${city.era}-era construction. This local fluency converts directly into shorter appointment times and higher success rates across ${city.area}.`,
  ];

  const p3variants = [
    `${city.localIssue}. Every completed ${svc} job in ${cn} comes with a 90-day parts and labour guarantee, a digital service summary emailed before our technician leaves, and live GPS tracking from the moment we dispatch. ${cn} households get the same service standard as downtown clients — at the same price, with the same warranty.`,
    `${city.localIssue}. After finishing ${svc} work at your ${cn} property, we issue a digital report documenting the diagnosis, parts used, and warranty terms. The 90-day workmanship guarantee covers every component we install. From dispatch to departure, ${cn} customers get real-time tracking updates so you know exactly when your technician will arrive.`,
    `${city.localIssue}. ${cn} customers receive a 90-day warranty on parts and labour, a digital service report accessible from any device, and GPS-based arrival tracking throughout the appointment window. We built this process specifically for ${city.area} homeowners who expect full accountability from their service providers.`,
    `${city.localIssue}. Once the ${svc} is complete at your ${cn} home, you receive an emailed service report with diagnosis details, replacement parts listed by model number, and your 90-day warranty confirmation. We dispatch to ${cn} with live tracking enabled so you can follow your technician's approach in real time.`,
  ];

  const p4variants = [
    `What separates Fixlify from other ${svc} companies operating in ${cn} is preparation. When our technician pulls up to your ${n[0]} or ${n[1]} property, they already know the standard plumbing layouts and electrical configurations found in ${cn}'s ${city.housing}. That familiarity translates into faster root-cause identification and more precise estimates. If a part needs to be ordered, we schedule the return visit at no additional charge — the follow-up is built into your original quote.`,
    `${cn} homeowners pick Fixlify for three reasons: we know ${city.area} housing, we quote honestly, and we stand behind our work. A technician arriving in ${n[0]} or ${n[2]} already understands the plumbing and electrical patterns typical of ${cn}'s ${city.housing}. That knowledge eliminates guesswork, shortens diagnosis, and produces quotes that match the final bill. If we need to source a part, the return trip costs you nothing extra.`,
    `For ${cn} residents, choosing Fixlify means choosing a company that invests in local expertise. Our technicians servicing ${n[0]}, ${n[1]}, and ${n.length>3?n[3]:n[2]} maintain detailed knowledge of the appliance brands, wiring vintages, and plumbing configurations prevalent across ${cn}'s ${city.housing}. The outcome is measurably faster diagnosis and reliable first-quote accuracy. Return visits for ordered parts are included at no added cost — a policy our ${cn} customers regularly cite as the reason they rebook.`,
    `The Fixlify advantage in ${cn} comes from specialisation. Our technicians running ${city.area} routes have handled thousands of ${svc} calls in ${cn}'s ${city.housing}, building pattern-recognition that generalist companies cannot match. When they step into your ${n[0]} or ${n[1]} kitchen, the diagnosis is faster because they have seen the same model, same wiring, same plumbing many times before. If a part is not on the truck, we order it and return within 48 hours at no extra service charge.`,
  ];

  const p5variants = [
    `Our ${svc} territory in ${cn} covers every pocket of ${city.area}: ${n.join(', ')}, and every street in between. Each ${cn} service vehicle carries a parts inventory selected from analysis of the appliance brands and common failures we encounter across this market. Specifically for ${svc}, our ${cn} completion rate on the initial appointment exceeds 85 percent. When we do need to order a component, we have it within 48 hours and return without adding a second service fee.`,
    `Fixlify dispatches to every part of ${cn} — ${n.slice(0,3).join(', ')}, ${n.length>3?n[3]+',':''} and beyond. Our service vehicles carry a locally curated parts selection based on ${cn}'s most common appliance models and documented failure patterns. For ${svc} specifically, more than 85 percent of ${cn} appointments end with the job finished on the same visit. Parts that need ordering arrive within two business days, and the installation visit carries no additional fee.`,
    `From ${n[0]} to ${n[n.length-1]}, Fixlify's ${cn} coverage is complete. We stock each service vehicle with parts selected from data on the appliance brands most installed in ${cn}'s ${city.housing}. This data-driven approach means our ${svc} first-visit success rate across ${cn} stays above 85 percent. For the small percentage of calls requiring a special-order part, we source and install within 48 hours — no repeat service charge.`,
    `${cn} ${svc} service extends across all of ${city.area}: ${n.slice(0,4).join(', ')}, and every adjacent neighbourhood. The parts inventory on each ${cn}-bound vehicle reflects thousands of past service calls — we know which brands break, which components fail, and what tools are needed before we arrive. This produces a first-appointment completion rate above 85 percent for ${svc} across ${cn}. On the rare occasion we need to order a part, it arrives within two days and the follow-up appointment is free.`,
  ];

  const p6variants = [
    `Most ${svc} calls from ${cn} homeowners involve units between three and eight years old. At this age, appliances have outlived their factory warranty but still have years of reliable service ahead. Targeted component replacement at $150-$250 is nearly always better economics than a $700-$1,100 new unit. We lay out both paths transparently: repair cost, expected remaining lifespan, and new-unit pricing. When a machine is genuinely beyond saving, we say so plainly — we would rather give you straight advice and earn a customer for life than sell a repair that will not last.`,
    `The typical ${cn} ${svc} request involves a unit that is four to seven years old — past the manufacturer's coverage but nowhere near end of life. For these appliances, component-level repair at $140-$280 almost always makes better financial sense than spending $800-$1,200 on a replacement. We explain both options clearly, including expected remaining lifespan after repair. If the machine has reached the point where repair would be wasteful, our technician tells you directly. Honest recommendations build the trust that keeps ${cn} families rebooking Fixlify year after year.`,
    `${cn} households most frequently call us for ${svc} on appliances in the four-to-nine-year range. These units sit in the sweet spot where factory warranties have expired but the machine still has significant useful life remaining. A $160-$300 repair that extends the unit's life by five to seven years beats purchasing a new $900-$1,300 appliance by any measure. We present the numbers honestly and let you choose. When an appliance is genuinely done, our technician says so — we prefer losing one repair fee to losing your trust.`,
    `In ${cn}, the bulk of our ${svc} work involves appliances aged three to ten years. These are machines worth fixing: the components that typically fail — motors, pumps, control boards, heating elements — cost a fraction of a new appliance and restore the unit to full function. We quote the repair, explain the expected lifespan after the fix, and let you compare against replacement cost. If the math does not support a repair, we tell you before charging anything beyond the $65 diagnostic. ${cn} homeowners value this honesty.`,
  ];

  const p7variants = [
    `Schedule ${svc} in ${cn} through our online portal — pick your appliance type, select a time slot, and get confirmation within seconds. ${cn} availability runs Monday to Saturday from 8 AM until 8 PM, and Sunday 9 AM to 6 PM. Morning slots for urgent work in ${n[0]} and other ${cn} neighbourhoods are released daily at 7 AM. Reach us at (437) 524-1053 if you prefer voice booking. Every appointment includes GPS-based arrival tracking.`,
    `Booking ${svc} in ${cn} takes under two minutes on our website. Choose the appliance category, select a day and time that works for your ${n[0]} or ${n[1]} schedule, and receive instant digital confirmation. Our ${cn} technicians work Monday through Saturday 8 AM to 8 PM, with Sunday hours from 9 AM to 6 PM. Same-day openings appear each morning for ${cn} residents who need fast turnaround. Phone bookings at (437) 524-1053 include the same live arrival tracking.`,
    `To book ${svc} in ${cn}, visit our scheduling page — select the appliance, choose your preferred time, and confirm. Done in under 120 seconds. ${cn} service hours: Monday-Saturday 8 AM-8 PM, Sunday 9 AM-6 PM. Urgent slots for ${n[0]}, ${n[1]}, and all ${cn} areas are posted every morning by 7 AM. You can also call (437) 524-1053 for same-day scheduling. GPS tracking is active from the moment dispatch confirms your appointment.`,
    `Ready to book? ${cn} ${svc} appointments are available online — select appliance type, pick a slot, confirm. The whole process takes about ninety seconds. We service ${cn} Monday through Saturday from 8 AM to 8 PM and Sunday from 9 AM until 6 PM. Same-day openings for ${n[0]} and neighbouring areas appear each morning. Call (437) 524-1053 for phone booking with real-time schedule availability. All ${cn} appointments include live technician tracking.`,
  ];

  const L = [];
  L.push(`<!-- UNIQUE-CITY-CONTENT -->`);
  L.push(`<div class="city-context" style="background:#F0F9FF;border-radius:8px;padding:24px 28px;margin:24px 0;">`);
  L.push(`<h3 style="font-size:1.125rem;font-weight:700;color:#0A0A0A;margin:0 0 12px;">${capSvc} Service Across ${cn}</h3>`);
  L.push(`<p style="${ps}">${pick(p1variants)}</p>`);
  L.push(`<p style="${ps}">${pick(p2variants)}</p>`);
  L.push(`<p style="${ps}">${pick(p3variants)}</p>`);
  L.push(`<h3 style="font-size:1.125rem;font-weight:700;color:#0A0A0A;margin:16px 0 12px;">Why ${cn} Residents Choose Fixlify for ${capSvc}</h3>`);
  L.push(`<p style="${ps}">${pick(p4variants)}</p>`);
  L.push(`<p style="${ps}">${pick(p5variants)}</p>`);
  L.push(`<p style="${ps}">${pick(p6variants)}</p>`);
  L.push(`<p style="margin:0;color:#374151;line-height:1.7;font-size:0.9375rem;">${pick(p7variants)}</p>`);
  L.push(`</div>`);
  L.push(`<!-- END-UNIQUE-CITY-CONTENT -->`);
  return '    ' + L.join('\n    ');
}

function replaceSharedSections(html, city) {
  const n = city.neighborhoods;
  const cn = city.name;
  const era = city.era;
  const area = city.area;
  const housing = city.housing;

  // ─── 1. Replace "What Our Dishwasher Installation Service Includes" ───
  const includesRx = /<h2>What Our Dishwasher Installation Service Includes<\/h2>\s*<p>When you book dishwasher installation[\s\S]*?<\/ul>/;
  if (includesRx.test(html)) {
    html = html.replace(includesRx, `<h2>How Fixlify Handles Dishwasher Installation in ${cn}</h2>
    <p>Dishwasher installation in ${cn}'s ${housing} follows a process refined across thousands of installations in ${area}. ${cn} homes present specific variables — ${city.waterNote} — and our technicians arrive prepared for conditions in ${n[0]}, ${n[1]}, and ${n[2]}. Here is what happens when our installer arrives at your ${cn} home:</p>
    <ul>
      <li><strong>Site assessment and old unit removal</strong> — Before touching a tool, our ${cn} installer checks water supply pressure, drain routing, and electrical circuit compatibility with your new dishwasher. If you have an old unit, we disconnect it, cap all connections, and remove it from your property. ${cn} homes from the ${era} era sometimes have corroded shut-off valves that we replace at no extra charge during removal.</li>
      <li><strong>Water and drain connections for ${cn} conditions</strong> — We connect the hot water supply using braided stainless steel lines rated for ${area} water pressure. The drain hose gets a proper high loop under the countertop to prevent backflow — critical in ${cn} where ${city.waterNote.split(' — ')[0].toLowerCase()}. Every connection is pressure-tested before proceeding.</li>
      <li><strong>Electrical hookup with local code compliance</strong> — Whether your ${cn} home requires hardwired or plug-in connection, our installer verifies circuit rating and tests for ground faults. ${cn} properties from the ${era} era sometimes need circuit upgrades that we coordinate when necessary.</li>
      <li><strong>Precision leveling for ${cn} housing stock</strong> — Floor irregularities are common in ${cn}'s ${housing}. We adjust leveling feet until the unit is perfectly balanced, then secure with mounting brackets. Proper leveling extends bearing life and prevents premature door seal wear in ${cn}'s specific housing conditions.</li>
      <li><strong>Complete test cycle with ${cn}-specific checks</strong> — We run a full wash cycle, inspect every connection for leaks, verify the drain pump engages, and confirm spray arms rotate freely. Your digital service report and 90-day warranty covering all workmanship are issued before we leave your ${cn} home.</li>
    </ul>`);
  }

  // ─── 2. Replace "Common Dishwasher Types We Install" ───
  const typesRx = /<h2>Common Dishwasher Types We Install<\/h2>\s*<p>Our [\w\s]+ installers are experienced[\s\S]*?<\/ul>/;
  if (typesRx.test(html)) {
    html = html.replace(typesRx, `<h2>Dishwasher Types Popular in ${cn} Homes</h2>
    <p>The dishwasher types installed most frequently in ${cn} reflect the neighbourhood's housing mix and homeowner priorities. ${cn}'s ${housing} create specific demands for different configurations, and choosing the right type for your kitchen is critical. Our ${cn} installers recommend based on actual kitchen dimensions in ${n[0]}, ${n[1]}, and surrounding areas:</p>
    <ul>
      <li><strong>Standard built-in 24-inch</strong> — The workhorse of ${cn} kitchens, especially in ${n[0]} and ${n[1]} homes. Samsung, LG, and Bosch are the most popular choices among ${cn} homeowners based on our installation data for ${area}.</li>
      <li><strong>Panel-ready integrated models</strong> — Increasingly popular in ${cn} kitchen renovations. ${cn}'s renovation boom has made Bosch and Miele panel-ready units our fastest-growing installation category in ${area}. Requires precise panel alignment that general handymen often get wrong.</li>
      <li><strong>Compact 18-inch slimline</strong> — Essential for ${cn} condos, smaller homes in ${n[2]}, and secondary kitchens in basement apartments. Same connections as standard but with specialized mounting brackets that we carry for all compact models.</li>
      <li><strong>Drawer dishwashers</strong> — Fisher & Paykel units gaining traction in ${cn}'s premium kitchen market, particularly in ${n.length>3?n[3]:n[0]}. These require different mounting, drain, and electrical approaches — our installers are factory-trained on drawer dishwasher installation.</li>
    </ul>`);
  }

  // ─── 3. Replace "Installation Types and Pricing in CITY" ───
  const pricingRx = new RegExp('<h2>Installation Types and Pricing in ' + cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '</h2>\\s*<p>Dishwasher installation complexity varies[\\s\\S]*?</ul>');
  if (pricingRx.test(html)) {
    html = html.replace(pricingRx, `<h2>Dishwasher Installation Pricing for ${cn} Residents</h2>
    <p>Installation costs in ${cn} depend on your home's existing infrastructure and job complexity. Homes in ${n[0]} and ${n[1]} with modern pre-plumbed layouts typically fall into standard installation pricing. Older ${cn} properties from the ${era} era or first-time installations require additional plumbing and electrical work. We provide a firm written quote specific to your ${cn} property before work begins — includes all labour, hardware, and supply lines with no add-on charges:</p>
    <ul>
      <li><strong>Standard installation for ${cn} homes with existing connections:</strong> $149 - $199 — Water supply, drain, and electrical already in place from a previous dishwasher or builder rough-in. Most ${cn} homes built after 1990 in ${n[0]} and ${n[1]} qualify.</li>
      <li><strong>Replacement installation with old unit removal in ${cn}:</strong> $199 - $249 — We disconnect and remove the old dishwasher, connect the new unit, and run a complete test cycle. The most common installation type across ${area}.</li>
      <li><strong>Complex installation for ${cn} properties:</strong> $299 - $399 — Required when your ${cn} home needs plumbing modifications, granite countertop mounting, panel-ready fitting, or first-time installation. Common in ${cn}'s older ${era} housing where kitchens did not originally include a dishwasher bay.</li>
    </ul>`);
  }

  // ─── 4. Replace "Step-by-Step: How We Install Your Dishwasher in CITY" (257w identical) ───
  const stepRx = new RegExp('<h2>Step-by-Step: How We Install Your Dishwasher in ' + cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '</h2>[\\s\\S]*?</ol>');
  if (stepRx.test(html)) {
    html = html.replace(stepRx, `<h2>Step-by-Step: How We Install Your Dishwasher in ${cn}</h2>
      <p>Every dishwasher installation in ${cn} follows a systematic process developed from our experience with ${housing} across ${area}. ${cn} properties in ${n[0]} and ${n[1]} present specific plumbing and electrical configurations that our installers account for at each stage. Here is the complete sequence for a ${cn} installation:</p>
      <ol>
        <li><strong>Water supply isolation for ${cn} homes:</strong> We locate the hot water shutoff valve, typically under the kitchen sink in ${cn}'s ${era}-era homes. ${cn} properties frequently have quarter-turn ball valves in newer builds or gate valves in older ${n[2]} and ${n.length>3?n[3]:n[0]} homes. If the valve shows corrosion or fails to seal completely, we replace it before proceeding — preventing future flood risk in your ${cn} home.</li>
        <li><strong>Old unit extraction in ${cn} kitchens:</strong> We detach the water supply line, drain hose, and power connection from the existing unit, then slide it out using felt pads to protect ${cn} homeowners' flooring. In ${n[0]} homes with hardwood or tile, we use extra protective layers during the removal process.</li>
        <li><strong>Installation bay inspection:</strong> We measure the cabinet opening, verify floor level across the bay width, and examine all existing connection points. ${cn} homes from the ${era} era commonly show specific wear patterns — ${city.localIssue.split(' — ')[0].toLowerCase()} — that we address before the new unit goes in.</li>
        <li><strong>New unit positioning in ${cn} cabinetry:</strong> The dishwasher slides into the opening with supply line, drain hose, and power cable routed through access holes. Our ${cn} installers leave service-access slack in every connection so future maintenance does not require full unit removal.</li>
        <li><strong>Hot water supply connection for ${area} conditions:</strong> We install a new braided stainless steel supply line from the shutoff valve to the dishwasher inlet valve. ${city.waterNote} — our ${cn} installers use Teflon tape rated for ${area} water conditions on every threaded joint.</li>
        <li><strong>Drain routing for ${cn} plumbing:</strong> The drain hose connects to the sink drain tailpiece or disposal inlet with a high loop secured to the underside of the countertop. This anti-siphon loop is critical in ${cn} homes where backflow prevention protects your kitchen from contaminated water return.</li>
        <li><strong>Electrical connection per Ontario code:</strong> Whether your ${cn} home uses a hardwired junction box or a dedicated outlet, our installer verifies the circuit amperage and tests for proper grounding. ${cn} homes in ${n[0]} and ${n[1]} built during the ${era} era may require electrical verification specific to their construction period.</li>
        <li><strong>Precision leveling for ${cn} floor conditions:</strong> ${cn}'s ${housing} often have slight floor variations. We adjust front and rear leveling feet until the unit reads perfectly level in both directions, then secure mounting brackets to the countertop underside or cabinet sides to prevent movement during operation.</li>
        <li><strong>Full test cycle with ${cn}-area water:</strong> We run a complete wash cycle monitoring fill volume, spray arm rotation, heating element activation, drain pump engagement, and drying performance. Every connection point is inspected for leaks during the cycle. We remain on-site until the test completes successfully and issue your digital service report with 90-day installation warranty.</li>
      </ol>`);
  }

  // ─── 5. Replace "When to Choose Professional Installation Over DIY" (131w identical) ───
  const diyRx = /<h2>When to Choose Professional Installation Over DIY<\/h2>[\s\S]*?<\/ul>/;
  if (diyRx.test(html)) {
    html = html.replace(diyRx, `<h2>Why ${cn} Homeowners Choose Professional Dishwasher Installation</h2>
      <p>While some homeowners attempt DIY dishwasher installation, ${cn} properties present specific challenges that make professional service the safer choice. Our experience with ${housing} across ${area} has shown these are the situations where DIY most commonly leads to problems:</p>
      <ul>
        <li><strong>First-time installation in ${cn} homes:</strong> Running new supply and drain lines in ${cn}'s ${era}-era construction requires knowledge of local plumbing configurations. Improper connections are the leading cause of kitchen water damage claims filed by ${area} homeowners with Ontario insurers.</li>
        <li><strong>Stone countertop kitchens in ${n[0]} and ${n[1]}:</strong> Granite, quartz, and marble countertops — common in ${cn}'s renovated kitchens — cannot accept standard top-mount brackets. Our installers use side-mount cabinet brackets that eliminate any risk to your countertop investment.</li>
        <li><strong>Panel-ready installations for ${cn} kitchen renovations:</strong> Integrated dishwashers from Bosch, Miele, and Thermador require precise door panel alignment specific to your ${cn} cabinetry. Misalignment causes both aesthetic issues and mechanical interference with door hinge mechanisms.</li>
        <li><strong>${cn}'s older housing stock:</strong> Properties built during the ${era} era in ${n[2]} and surrounding ${cn} neighbourhoods may have galvanized steel drain pipes, older copper supply lines, or undersized electrical circuits that require professional assessment before connecting modern appliances.</li>
        <li><strong>Condo installations in ${cn}:</strong> ${cn} building management companies typically require proof of professional installation and may hold unit owners liable for water damage from DIY connections. Our installation receipt satisfies building management requirements across ${area}.</li>
      </ul>`);
  }

  // ─── 6. Replace "Brands We Install in CITY" (109w identical) ───
  const brandsRx = new RegExp('<h2>Brands We Install in ' + cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '</h2>[\\s\\S]*?</ul>');
  if (brandsRx.test(html)) {
    html = html.replace(brandsRx, `<h2>Dishwasher Brands Our ${cn} Installers Handle</h2>
      <p>Fixlify installs dishwashers from every manufacturer sold in ${area}. Our ${cn} service vehicles carry brand-specific mounting brackets, connection hardware, and panel-fitting tools. Based on our ${cn} installation data, here are the brands we install most frequently in ${n[0]}, ${n[1]}, and across ${cn}:</p>
      <ul>
        <li><strong>Bosch</strong> — 300, 500, 800, and Benchmark series installation in ${cn}. Panel-ready and freestanding configurations. AquaStop flood protection verification included with every ${cn} Bosch installation.</li>
        <li><strong>Samsung</strong> — Linear Wash, StormWash, and Smart series. Wi-Fi connectivity setup included for ${cn} homeowners at no extra charge. Popular upgrade choice in ${n[0]} kitchen renovations.</li>
        <li><strong>LG</strong> — QuadWash, TrueSteam, and Studio series installation across ${cn}. Smart ThinQ app connectivity configuration included. Growing in popularity among ${cn}'s tech-forward homeowners.</li>
        <li><strong>Whirlpool</strong> — Standard, quiet-partner, and third-rack models. The most frequently replaced brand in ${cn}'s ${era}-era builder-grade kitchens across ${n[1]} and ${n[2]}.</li>
        <li><strong>Miele</strong> — G7000, Classic, and ProfiLine series for ${cn}'s premium market. Requires specialized mounting procedure and AquaStop activation that general installers often miss.</li>
        <li><strong>KitchenAid</strong> — FreeFlex, standard, and panel-ready configurations. A popular mid-range upgrade choice for ${cn} homeowners replacing older units in ${n[0]} and surrounding areas.</li>
        <li><strong>GE and GE Profile</strong> — Standard, Fingerprint Resistant, and UltraFresh models. Common in ${cn}'s builder-grade homes across ${area}, especially in newer ${n.length>4?n[4]:n[2]} developments.</li>
        <li><strong>Fisher & Paykel</strong> — Single and double drawer dishwashers for ${cn}'s premium and compact kitchen market. Unique drawer-pull mechanism requires specialized installation training.</li>
      </ul>`);
  }

  // ─── 7. Replace "What We Handle During Installation" / problems-grid (81w identical) ───
  const handleRx = /<h2 class="section-title">What We Handle During Installation<\/h2>\s*<div class="problems-grid">(?:\s*<div class="problem-card">[\s\S]*?<\/div>\s*<\/div>)+\s*<\/div>/;
  if (handleRx.test(html)) {
    html = html.replace(handleRx, `<h2 class="section-title">What Our ${cn} Installers Handle</h2>
    <div class="problems-grid">
      <div class="problem-card">
        <div class="problem-name">Old Unit Removal in ${cn}</div>
        <div class="problem-desc">We disconnect water, drain, and electrical from your existing dishwasher, remove and dispose of it. ${cn} homes from the ${era} era sometimes require extra care with corroded connection points.</div>
      </div>
      <div class="problem-card">
        <div class="problem-name">${cn} Plumbing Connection</div>
        <div class="problem-desc">Hot water supply line installation, drain hose routing with anti-siphon high loop, and shutoff valve inspection. ${area} water conditions factored into material selection.</div>
      </div>
      <div class="problem-card">
        <div class="problem-name">Electrical for ${cn} Homes</div>
        <div class="problem-desc">Hardwired or plug-in connection per Ontario Electrical Code, circuit amperage verification, and ground fault testing specific to ${cn}'s ${era}-era wiring standards.</div>
      </div>
      <div class="problem-card">
        <div class="problem-name">Leveling for ${cn} Floors</div>
        <div class="problem-desc">Precision leveling with adjustable feet to compensate for floor variations common in ${cn}'s ${housing}. Mounting brackets secured to prevent movement.</div>
      </div>
      <div class="problem-card">
        <div class="problem-name">Panel-Ready Fitting in ${cn}</div>
        <div class="problem-desc">Custom door panel alignment for integrated dishwashers matching your ${cn} kitchen cabinetry. Popular in ${n[0]} and ${n[1]} renovation projects.</div>
      </div>
      <div class="problem-card">
        <div class="problem-name">${cn} Test Cycle</div>
        <div class="problem-desc">Complete wash cycle with ${area} water, leak inspection at every connection, spray arm verification, and drain pump test before sign-off at your ${cn} home.</div>
      </div>
    </div>`);
  }

  // ─── 8. Replace "After Installation: What to Expect" (79w identical) ───
  const afterRx = /<h2>After Installation: What to Expect<\/h2>[\s\S]*?<\/ul>/;
  if (afterRx.test(html)) {
    html = html.replace(afterRx, `<h2>After Your ${cn} Dishwasher Installation</h2>
      <p>Once your new dishwasher is installed in your ${cn} home and the test cycle confirms proper operation, follow these steps for optimal performance:</p>
      <ul>
        <li>Run two to three empty hot cycles with dishwasher cleaner to flush manufacturing residue and break in the spray arm bearings before loading dishes for the first time.</li>
        <li>Add rinse aid from the very first loaded cycle — ${city.waterNote.split('.')[0]}. Without rinse aid, ${cn}'s water conditions will leave visible spots on glassware and flatware.</li>
        <li>Check the door seal alignment after your first three loaded cycles. If you notice any moisture around the door edges in your ${cn} kitchen, call us for a complimentary adjustment — minor leveling tweaks resolve this in most ${area} installations.</li>
        <li>Store your Fixlify service receipt from the ${cn} installation — it documents your 90-day workmanship warranty, the unit serial number, and all connection specifications for future reference by any service technician.</li>
      </ul>`);
  }

  // ─── 9. Replace "Dishwasher Installation Cost in CITY" table (58w identical) ───
  const costRx = new RegExp('<h2 class="section-title">Dishwasher Installation Cost in ' + cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '</h2>\\s*<table class="pricing-table"[\\s\\S]*?</table>\\s*<p class="pricing-note">[\\s\\S]*?</p>');
  if (costRx.test(html)) {
    html = html.replace(costRx, `<h2 class="section-title">Dishwasher Installation Cost in ${cn}</h2>
    <table class="pricing-table" aria-label="Installation pricing for ${cn}">
      <thead><tr><th>Installation Type for ${cn} Homes</th><th>Price Range</th></tr></thead>
      <tbody>
        <tr><td>Standard installation in ${cn} (existing water, drain, electrical connections from previous unit)</td><td>$149 &ndash; $199</td></tr>
        <tr><td>Replacement installation in ${cn} (remove old dishwasher + install and connect new unit)</td><td>$199 &ndash; $249</td></tr>
        <tr><td>Complex installation for ${cn} properties (plumbing modifications, stone countertop, panel-ready)</td><td>$299 &ndash; $399</td></tr>
        <tr><td>First-time dishwasher installation in ${cn} (no previous unit, new plumbing and electrical required)</td><td>$299 &ndash; $399</td></tr>
      </tbody>
    </table>
    <p class="pricing-note">All ${cn} installation prices include labour, mounting hardware, braided stainless steel supply line, and drain connection materials. Custom door panels for panel-ready units are sourced from your ${cn} cabinetmaker. Written quote provided before work begins — the price we quote is the price you pay for your ${n[0]} or ${n[1]} installation.</p>`);
  }

  // ─── 10. Replace FAQ section (185w identical) ───
  // Use indexOf-based approach since regex escaping is tricky with nested divs
  const faqHeader = 'Frequently Asked Questions \u2014 Dishwasher Installation in ' + cn;
  const faqHeaderAlt = 'Frequently Asked Questions — Dishwasher Installation in ' + cn;
  const faqRx = /<h2>Frequently Asked Questions[\s\S]*?<\/details>\s*<\/div>\s*<\/div>/;
  if (faqRx.test(html)) {
    html = html.replace(faqRx, `<h2>Frequently Asked Questions — Dishwasher Installation in ${cn}</h2>
      <div class="faq-list">
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">How much does dishwasher installation cost in ${cn}?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Standard dishwasher installation in ${cn} costs $149-$199 when connecting to existing plumbing in ${n[0]}, ${n[1]}, or other ${cn} neighbourhoods. Replacement installation removing an old unit and connecting a new one runs $199-$249. Complex installations in ${cn}'s ${era}-era homes that need plumbing modifications, stone countertop brackets, or panel-ready fitting cost $299-$399. We provide a written quote specific to your ${cn} property before starting.</p></div></details>
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">Can I get same-day dishwasher installation in ${cn}?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Yes — call (437) 524-1053 before 2 PM to check same-day availability for ${cn}. Our ${area} installers carry all mounting brackets, supply lines, and connection hardware on every appointment so your ${cn} installation is completed in a single visit without waiting for parts or a follow-up trip.</p></div></details>
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">What is included in a ${cn} dishwasher installation?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Our ${cn} installation includes: removal and disposal of your old dishwasher, positioning the new unit in the cabinet opening, connecting the hot water supply line from the shutoff valve, routing the drain hose with an anti-siphon high loop, making the electrical connection per Ontario code, precision leveling for ${cn}'s floor conditions, securing with mounting brackets, and running a complete test cycle to verify every connection.</p></div></details>
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">Can you install a dishwasher where there was never one in my ${cn} home?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Yes — first-time dishwasher installation is one of our specialties across ${cn}. We create the cabinet opening if your ${cn} kitchen needs one, run a hot water supply line from the under-sink shutoff to the dishwasher location, route a drain connection to the sink drain, and verify the electrical circuit capacity meets the unit's requirements. First-time installations in ${cn} typically cost $299-$399 and take 2-3 hours to complete properly.</p></div></details>
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">Do I need to buy my own dishwasher before booking ${cn} installation?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Yes — purchase your new dishwasher from any retailer and have it delivered to your ${cn} home. We handle the professional installation only. If you need sizing advice for your ${cn} kitchen layout — especially in ${n[0]} or ${n[1]} homes with non-standard cabinet dimensions — call (437) 524-1053 and our team can recommend the right measurements before you buy.</p></div></details>
        <details class="faq-item"><summary class="faq-question"><span class="faq-q-text">What warranty covers the ${cn} installation work?</span><span class="faq-icon" aria-hidden="true">+</span></summary><div class="faq-answer"><p>Every ${cn} installation by Fixlify includes a 90-day warranty covering our workmanship — all plumbing connections, electrical connections, and mounting brackets installed at your ${cn} property. If any connection we made develops an issue within 90 days, we return to your ${cn} home and fix it at no additional charge. The dishwasher itself remains covered by the manufacturer's warranty.</p></div></details>
      </div>
    </div>`);
  }

  // ─── 11. Replace answer-box text (46w identical) ───
  const answerBoxRx = /class="answer-box">Need dishwasher installation in [^?]+\?[^<]+<\/div>/;
  if (answerBoxRx.test(html)) {
    const answerVariants = [
      `class="answer-box">Looking for professional dishwasher installation in ${cn}? Fixlify handles same-day dishwasher fitting across ${n[0]}, ${n[1]}, and all ${cn} neighbourhoods. Pricing: standard hookup $149-$199, full replacement $199-$249, complex jobs $299-$399. We install Samsung, LG, Bosch, Whirlpool, Miele, KitchenAid, and more. Fully licensed, insured, 90-day warranty on all connections. Book now: (437) 524-1053.</div>`,
      `class="answer-box">${cn} dishwasher installation by Fixlify — available same-day in ${n[0]}, ${n[1]}, ${n[2]}, and surrounding ${cn} areas. Standard install from $149, replacement from $199, complex from $299. Every major brand: Samsung, LG, Bosch, Whirlpool, Miele, KitchenAid. Licensed technicians, insured service, 90-day workmanship guarantee. Call (437) 524-1053 to schedule.</div>`,
      `class="answer-box">Fixlify installs dishwashers across ${cn} — ${n[0]}, ${n[1]}, ${n[2]} and beyond. Same-day appointments available. Standard installation $149-$199, replacement with old unit removal $199-$249, complex installations $299-$399. All major dishwasher brands serviced. Licensed, insured, with a 90-day installation warranty. Schedule today: (437) 524-1053.</div>`,
      `class="answer-box">Professional dishwasher installation for ${cn} homes — Fixlify covers ${n[0]}, ${n[1]}, and every ${cn} neighbourhood. Same-day service available. Install pricing: basic $149-$199, replacement $199-$249, complex $299-$399. Samsung, LG, Bosch, Whirlpool, Miele, and all other brands. Licensed, insured, 90-day guarantee. Reach us: (437) 524-1053.</div>`,
    ];
    let abHash = 0;
    for (let i = 0; i < cn.length; i++) abHash = ((abHash << 3) + cn.charCodeAt(i)) | 0;
    html = html.replace(answerBoxRx, answerVariants[((abHash >>> 0) + 5) % answerVariants.length]);
  }

  // ─── 12. Replace "Book Dishwasher Installation in CITY" text ───
  const bookRx = new RegExp('<h2>Book Dishwasher Installation in ' + cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '</h2>\\s*<p>Choose a convenient time');
  if (bookRx.test(html)) {
    const bookVariants = [
      `<h2>Schedule Your ${cn} Dishwasher Installation</h2>\n    <p>Pick a time that works for your ${n[0]} or ${n[1]} schedule &mdash; our online booking shows real-time availability with instant confirmation.</p>`,
      `<h2>Book Dishwasher Installation in ${cn} Online</h2>\n    <p>Select your preferred installation date and time slot below &mdash; live availability for all ${cn} neighbourhoods with instant booking confirmation.</p>`,
      `<h2>Reserve Your ${cn} Installation Appointment</h2>\n    <p>Choose a convenient day and time for your ${cn} dishwasher installation &mdash; see what is available right now and confirm in seconds.</p>`,
      `<h2>Get Your ${cn} Dishwasher Installed</h2>\n    <p>Book online below for same-day or next-day installation across ${cn} &mdash; real-time scheduling with immediate confirmation for ${n[0]}, ${n[1]}, and all areas.</p>`,
    ];
    let bkHash = 0;
    for (let i = 0; i < cn.length; i++) bkHash = ((bkHash << 4) + cn.charCodeAt(i)) | 0;
    html = html.replace(bookRx, bookVariants[((bkHash >>> 0) + 3) % bookVariants.length]);
  }

  return html;
}
